/* Generated by scripts/build-items.py from web research: complete kit lists per guide (TB.KITS)
   and the item dictionary (TB.ITEMS). Do not edit by hand. */
window.TB = window.TB || {};
TB.ITEMS = {
"baking-soda": {
"name": "Baking soda",
"kind": "consumable",
"what": "Common sodium bicarbonate that neutralizes battery acid when mixed with water.",
"uses": [
"Cleaning corroded battery terminals",
"Neutralizing acid spills"
],
"tip": "Mix about 1 tablespoon per cup of water; rinse and dry after it stops fizzing."
},
"bike-stand": {
"name": "Bike repair stand",
"kind": "tool",
"what": "A clamp stand that holds the bike off the ground at working height.",
"uses": [
"Wheel removal",
"Brake and chain work",
"Spinning wheels to test"
],
"tip": "Clamp the seatpost, not the frame tubes, especially on carbon bikes."
},
"brake-pads-rim": {
"name": "Rim brake pads",
"kind": "part",
"what": "Rubber blocks or cartridge inserts that press on the wheel rim to stop the bike; compound must suit alloy or carbon rims.",
"uses": [
"Replacing worn pads",
"Upgrading stopping power"
],
"tip": "Replace when the wear grooves are almost gone; carbon rims need carbon-specific pads."
},
"bucket": {
"name": "Bucket",
"kind": "tool",
"what": "A pail for water or catching drips.",
"uses": [
"Rinsing after degreasing",
"Holding cleaning water"
],
"tip": "Use a separate bucket for degreaser rinse so it does not contaminate wash water."
},
"car-jack": {
"name": "Car jack",
"kind": "tool",
"what": "A scissor or bottle jack that lifts one corner of a vehicle so a wheel can be removed.",
"uses": [
"Changing a flat tire",
"Short roadside lifts"
],
"tip": "Use only on firm, level ground at the maker's jack point, and never get under a car held only by a jack."
},
"chain-checker": {
"name": "Chain wear checker",
"kind": "measure",
"what": "A gauge that drops into the chain to show stretch, usually at 0.5 and 0.75 percent.",
"uses": [
"Deciding when to replace a chain",
"Protecting cassette and chainrings"
],
"tip": "Replace at 0.5 percent on 11 or 12-speed and 0.75 percent on fewer speeds to save the cassette."
},
"chain-lube": {
"name": "Bike chain lubricant",
"kind": "material",
"what": "A drip-on oil or wax lube for bicycle chains; wet types for rain, dry types for dusty conditions.",
"uses": [
"Lubricating chain rollers",
"Quieting squeaks"
],
"tip": "One drop per roller is enough; always wipe the outside dry so it does not attract dirt."
},
"chain-scrubber": {
"name": "Chain scrubber",
"kind": "tool",
"what": "A clip-on box with rotating brushes and a degreaser reservoir that cleans a chain on the bike.",
"uses": [
"Deep-cleaning a grimy chain"
],
"tip": "Put a pan or rag under it; degreaser drips as you pedal."
},
"chalk-or-marker": {
"name": "Marker or chalk",
"kind": "consumable",
"what": "Something to mark a spot on the tire or tube.",
"uses": [
"Marking a puncture location",
"Aligning tire label with valve"
],
"tip": "Mount the tire with the label at the valve so you can match tube holes to tire damage."
},
"degreaser": {
"name": "Bike degreaser",
"kind": "material",
"what": "A solvent or citrus/water-based cleaner that dissolves old lube and grit.",
"uses": [
"Cleaning a dirty chain",
"Cassette and chainring cleaning"
],
"tip": "Rinse and dry the chain completely before lubing; leftover degreaser thins the lube."
},
"donor-vehicle": {
"name": "Helper vehicle",
"kind": "tool",
"what": "A running car or truck with a healthy battery of the same voltage (12 V) used to supply power during a jump start.",
"uses": [
"Jump-starting a dead battery",
"Recharging a weak battery briefly"
],
"tip": "Check both are 12 V systems; never jump a car from a hybrid or EV unless its manual says it is allowed."
},
"drop-cloth": {
"name": "Drop cloth or cardboard",
"kind": "consumable",
"what": "A cover laid on the floor to catch drips.",
"uses": [
"Catching lube and degreaser drips",
"Protecting garage floors"
],
"tip": "Flattened cardboard is free and soaks up oil."
},
"engine-coolant": {
"name": "Engine coolant (antifreeze)",
"kind": "material",
"what": "A glycol-based fluid that keeps the engine from overheating or freezing; formulas (OAT, HOAT, etc.) are vehicle-specific.",
"uses": [
"Topping up the overflow reservoir",
"Cooling system service"
],
"tip": "Use the type the manual specifies, usually premixed 50/50; never open a hot radiator cap."
},
"flashlight": {
"name": "Flashlight or headlamp",
"kind": "tool",
"what": "A portable light; a headlamp keeps both hands free.",
"uses": [
"Finding battery terminals and jack points",
"Roadside work at night",
"Reading reservoir marks"
],
"tip": "A headlamp beats a flashlight for any job that needs two hands."
},
"floor-pump": {
"name": "Floor pump with gauge",
"kind": "tool",
"what": "A standing bike pump with a pressure gauge and a head that fits Presta and/or Schrader valves.",
"uses": [
"Inflating to sidewall pressure",
"Seating tire beads"
],
"tip": "Choose a dual head that fits both valve types; a mini pump or CO2 inflator is the on-ride option."
},
"funnel": {
"name": "Funnel",
"kind": "tool",
"what": "A cone that guides liquid into a narrow opening without spilling.",
"uses": [
"Adding oil",
"Adding coolant or washer fluid"
],
"tip": "Keep separate funnels for oil and coolant to avoid cross-contamination."
},
"glass-cleaner": {
"name": "Glass cleaner",
"kind": "consumable",
"what": "A streak-free cleaner for automotive glass.",
"uses": [
"Cleaning the windshield before new wipers",
"Wiping blade edges"
],
"tip": "Rubbing alcohol on a rag also cleans grime off the new blade's rubber edge."
},
"hex-key-set": {
"name": "Hex key set",
"kind": "tool",
"what": "L-shaped Allen wrenches in metric sizes (commonly 2 to 10 mm) for bike bolts.",
"uses": [
"Brake caliper and pad bolts",
"Seat and stem bolts",
"Through-axles"
],
"tip": "Ball-end keys reach at angles but use the short straight end for final tightening."
},
"inner-tube": {
"name": "Inner tube",
"kind": "part",
"what": "The inflatable rubber tube inside a bicycle tire; sized to the tire (for example 700x25c or 26x2.1) with a Presta or Schrader valve.",
"uses": [
"Replacing a punctured tube",
"Carrying a spare on rides"
],
"tip": "Match the size printed on the tire sidewall and the valve type and length to your rim."
},
"isopropyl-alcohol": {
"name": "Isopropyl (rubbing) alcohol",
"kind": "consumable",
"what": "A solvent that evaporates fully, leaving no residue on braking surfaces.",
"uses": [
"Cleaning rims and pads",
"Degreasing disc rotors",
"Cleaning wiper rubber"
],
"tip": "Use 70 to 99 percent; higher purity evaporates faster."
},
"jump-starter-pack": {
"name": "Portable jump starter",
"kind": "power-tool",
"what": "A rechargeable lithium battery pack with built-in clamps that can start a car without a second vehicle.",
"uses": [
"Jump-starting alone",
"Charging phones in an emergency",
"Backup in a winter kit"
],
"tip": "Recharge it every 3 months; a pack left dead in the trunk is useless when you need it."
},
"jumper-cables": {
"name": "Jumper cables",
"kind": "tool",
"what": "A pair of heavy insulated copper cables with red and black spring clamps that connect a good battery to a dead one so it can start.",
"uses": [
"Jump-starting a car with a dead battery",
"Helping another driver",
"Emergency kit staple"
],
"tip": "Buy 4 to 6 gauge (lower number is thicker) and at least 12 to 16 ft long; thin 10-gauge sets struggle in the cold."
},
"kneeling-pad": {
"name": "Kneeling pad",
"kind": "safety",
"what": "A foam pad to kneel on, protecting knees and clothes.",
"uses": [
"Roadside tire changes",
"Working on low parts"
],
"tip": "A folded floor mat from the car works in a pinch."
},
"lug-wrench": {
"name": "Lug wrench",
"kind": "tool",
"what": "An L-shaped or cross-shaped wrench with a socket that fits wheel lug nuts.",
"uses": [
"Loosening and tightening lug nuts",
"Roadside tire changes"
],
"tip": "A 4-way cross wrench gives more leverage and fits common 17, 19, 21 mm and 13/16, 3/4″ sizes."
},
"motor-oil": {
"name": "Motor oil",
"kind": "material",
"what": "Engine oil that lubricates and cools moving parts; grade (for example 0W-20) and spec (API/ILSAC or maker approval) must match the owner's manual.",
"uses": [
"Topping up a low engine",
"Oil changes"
],
"tip": "Buy the exact viscosity and approval listed in the manual or on the oil cap; keep one quart in the trunk."
},
"nitrile-gloves": {
"name": "Nitrile gloves",
"kind": "safety",
"what": "Thin disposable gloves that keep oil, coolant, solvents and grease off your skin.",
"uses": [
"Adding oil and coolant",
"Degreasing a bike chain",
"Handling brake parts"
],
"tip": "Choose powder-free 5 to 8 mil gloves; thicker ones tear less on sharp parts."
},
"open-end-wrench": {
"name": "Open-end wrench",
"kind": "tool",
"what": "A flat wrench, usually 8 to 10 mm, for nuts on bike brakes and axles.",
"uses": [
"Brake caliper nuts",
"Older pad studs",
"Axle nuts on non-quick-release wheels"
],
"tip": "A 10 mm wrench fits most rim-brake pad nuts."
},
"owners-manual": {
"name": "Owner's manual",
"kind": "material",
"what": "The vehicle's printed or online guide listing specs, fluid types, jack points and procedures.",
"uses": [
"Finding jack points and lug torque",
"Checking oil and coolant type",
"Jump-start terminal locations"
],
"tip": "Download a PDF copy from the maker's website to your phone as a backup."
},
"patch-kit": {
"name": "Tube patch kit",
"kind": "material",
"what": "A kit of rubber patches, sandpaper and sometimes vulcanizing glue for sealing tube punctures.",
"uses": [
"Repairing punctured tubes",
"Backup when spares run out"
],
"tip": "Glue-type patches last longer than self-adhesive ones; let the glue dry until dull before applying."
},
"pick-tool": {
"name": "Pick or awl",
"kind": "tool",
"what": "A pointed tool for digging out small debris.",
"uses": [
"Removing embedded glass or metal from brake pads",
"Finding thorns in tires"
],
"tip": "Work gently to avoid gouging rubber."
},
"rag": {
"name": "Rag",
"kind": "consumable",
"what": "A reusable cotton cloth for wiping grease and dirt.",
"uses": [
"Wiping a bike chain",
"Cleaning rims",
"Wiping hands"
],
"tip": "Use a separate clean rag for rims and brake surfaces so you do not spread lube onto them."
},
"reflective-triangle": {
"name": "Warning triangle",
"kind": "safety",
"what": "A folding reflective triangle placed behind a stopped vehicle to warn traffic.",
"uses": [
"Roadside flat tires",
"Breakdowns at night"
],
"tip": "Place it about 100 to 300 ft behind the car depending on road speed."
},
"reflective-vest": {
"name": "Reflective vest",
"kind": "safety",
"what": "A high-visibility vest that makes you easier to see beside a road.",
"uses": [
"Roadside tire changes",
"Night breakdowns"
],
"tip": "Keep it in the cabin, not the trunk, so you can put it on before getting out."
},
"safety-glasses": {
"name": "Safety glasses",
"kind": "safety",
"what": "Impact-rated clear eye protection that wraps around the eyes.",
"uses": [
"Working near batteries",
"Under-car work with falling debris",
"Spraying cleaners or degreasers"
],
"tip": "Look for ANSI Z87.1 marking on the frame."
},
"sandpaper": {
"name": "Fine sandpaper or emery cloth",
"kind": "consumable",
"what": "Abrasive paper that removes glaze and grit.",
"uses": [
"Deglazing brake pads",
"Scuffing tubes before patching"
],
"tip": "Lightly sand glazed pads; do not sand rims heavily."
},
"shop-towels": {
"name": "Shop towels",
"kind": "consumable",
"what": "Heavy, lint-light paper or cloth towels for wiping hands, parts and spills.",
"uses": [
"Wiping dipsticks",
"Cleaning up drips",
"Drying parts"
],
"tip": "Lint-free towels are best for dipsticks so fibers do not end up in the engine."
},
"small-container": {
"name": "Small parts container",
"kind": "consumable",
"what": "A cup, tray or magnetic bowl that holds small parts so they do not roll away.",
"uses": [
"Holding lug nuts",
"Keeping bolts organized"
],
"tip": "A magnetic parts tray grips steel nuts even on a slope."
},
"socket-set": {
"name": "Socket set",
"kind": "tool",
"what": "A ratchet handle with interchangeable sockets in many sizes.",
"uses": [
"Lug nuts with a torque wrench",
"Battery terminals",
"General car repair"
],
"tip": "A 1/2″-drive deep socket matching your lug nuts pairs with a torque wrench for wheels."
},
"spare-tire": {
"name": "Spare tire",
"kind": "part",
"what": "A full-size or compact temporary wheel and tire stored in the vehicle for replacing a flat.",
"uses": [
"Replacing a flat to get to a shop"
],
"tip": "Check its pressure monthly; compact spares often need 60 psi and are limited to about 50 mph."
},
"stiff-brush": {
"name": "Stiff bristle brush",
"kind": "tool",
"what": "A nylon-bristle scrub brush for drivetrain grime.",
"uses": [
"Scrubbing chains, cogs and chainrings",
"Cleaning tire treads"
],
"tip": "An old toothbrush reaches between cogs."
},
"tape-measure": {
"name": "Tape measure",
"kind": "measure",
"what": "A retractable measuring tape.",
"uses": [
"Measuring wiper blade length",
"Bike tire size checks"
],
"tip": "For wipers, measure the rubber end to end in inches."
},
"tire-levers": {
"name": "Tire levers",
"kind": "tool",
"what": "Flat plastic hooks that pry a bicycle tire bead off and over the rim without damaging the tube.",
"uses": [
"Removing bike tires",
"Installing tight tires"
],
"tip": "Use plastic levers, not screwdrivers, which pinch tubes and scratch rims."
},
"tire-pressure-gauge": {
"name": "Tire pressure gauge",
"kind": "measure",
"what": "A small gauge that reads air pressure in a tire in psi.",
"uses": [
"Checking the spare before driving",
"Monthly tire checks",
"Setting bike tire pressure"
],
"tip": "Check tires cold, using the pressure on the driver's door-jamb sticker, not the tire sidewall maximum."
},
"torque-wrench": {
"name": "Torque wrench",
"kind": "measure",
"what": "A wrench that tightens fasteners to a specific measured force, usually clicking when reached.",
"uses": [
"Lug nuts to spec",
"Bike bolts in newton-meters",
"Engine and brake fasteners"
],
"tip": "Store click-type wrenches at their lowest setting so the spring stays accurate."
},
"towel": {
"name": "Towel",
"kind": "consumable",
"what": "A folded bath or shop towel used as padding or for wiping.",
"uses": [
"Protecting the windshield under a wiper arm",
"Drying parts"
],
"tip": "Fold it thick; a wiper arm snapping onto bare glass can crack it."
},
"valve-adapter": {
"name": "Presta-to-Schrader adapter",
"kind": "tool",
"what": "A small brass fitting that lets a Presta valve be filled with a car-style Schrader pump.",
"uses": [
"Using gas-station air on Presta",
"Using older pumps"
],
"tip": "Keep one on the valve cap of a spare tube."
},
"washer-fluid": {
"name": "Windshield washer fluid",
"kind": "material",
"what": "A water and alcohol cleaning solution sprayed on the windshield, often rated to resist freezing.",
"uses": [
"Filling the washer reservoir",
"Cleaning windows"
],
"tip": "Use a winter blend rated to -20 °F or lower in cold climates; plain water can freeze and crack the reservoir."
},
"wheel-chock": {
"name": "Wheel chock",
"kind": "safety",
"what": "A wedge placed against a tire to stop the vehicle from rolling.",
"uses": [
"Securing the car before jacking",
"Parking on slopes",
"Trailer work"
],
"tip": "Chock the wheel diagonally opposite the one being lifted, on both sides of the tire if possible."
},
"wheel-lock-key": {
"name": "Wheel lock key",
"kind": "tool",
"what": "A special keyed socket required to remove a locking lug nut, if your wheels have one.",
"uses": [
"Removing locking lug nuts"
],
"tip": "Keep it in the glovebox or with the jack; shops cannot remove locks easily without it."
},
"wiper-blade": {
"name": "Wiper blade",
"kind": "part",
"what": "The rubber-edged arm insert that sweeps the windshield clear; sold by length and connector type.",
"uses": [
"Replacing streaking or chattering blades",
"Seasonal replacement"
],
"tip": "Measure each side or use a store's fit guide; driver and passenger lengths often differ."
},
"wire-brush": {
"name": "Wire brush",
"kind": "tool",
"what": "A brush with stiff steel or brass bristles for scrubbing corrosion and rust.",
"uses": [
"Cleaning battery terminals",
"Removing rust from wheel hubs",
"Cleaning threads"
],
"tip": "A dedicated battery-terminal brush cleans both posts and clamps."
},
"work-gloves": {
"name": "Work gloves",
"kind": "safety",
"what": "Durable fabric or leather gloves that protect hands from cuts, heat and grime.",
"uses": [
"Handling wheels and lug nuts",
"Jumper cable clamps",
"Gripping greasy parts"
],
"tip": "Keep a pair in the trunk with your spare-tire tools."
}
};
TB.KITS = {
"jump-start": {
"items": [
{
"key": "jumper-cables",
"name": "Jumper cables",
"spec": "4 to 6 gauge, 12 to 20 ft",
"kind": "tool"
},
{
"key": "donor-vehicle",
"name": "Helper vehicle",
"spec": "running vehicle, same 12 V system",
"kind": "tool"
},
{
"key": "jump-starter-pack",
"name": "Portable jump starter",
"spec": "optional alternative to helper car, rated for your engine size",
"kind": "power-tool"
},
{
"key": "safety-glasses",
"name": "Safety glasses",
"spec": "",
"kind": "safety"
},
{
"key": "work-gloves",
"name": "Work gloves",
"spec": "insulated or leather",
"kind": "safety"
},
{
"key": "wire-brush",
"name": "Wire brush",
"spec": "battery terminal brush",
"kind": "tool"
},
{
"key": "baking-soda",
"name": "Baking soda",
"spec": "about 1 tbsp per cup of water, for corroded terminals",
"kind": "consumable"
},
{
"key": "shop-towels",
"name": "Shop towels",
"spec": "",
"kind": "consumable"
},
{
"key": "flashlight",
"name": "Flashlight or headlamp",
"spec": "headlamp preferred",
"kind": "tool"
},
{
"key": "owners-manual",
"name": "Owner's manual",
"spec": "for terminal and ground-point locations",
"kind": "material"
}
],
"proTips": [
"Do not crank the dead car for more than about 20 seconds at a time; wait a minute or two between tries so the starter cools and the battery gets more charge.",
"If the battery case is cracked, bulging, leaking or frozen, do not jump it; it can rupture or explode.",
"After a successful jump, drive at least 20 to 30 minutes or put the battery on a charger, and have it load-tested; a battery that needed one jump often needs replacing."
],
"sources": [
"https://cluballiance.aaa.com/the-extra-mile/articles/prepare/car/how-to-use-jumper-cables",
"https://www.colorado.aaa.com/automotive/jump-starting-car",
"https://www.edmunds.com/how-to/jump-start.html"
]
},
"flat-tire": {
"items": [
{
"key": "spare-tire",
"name": "Spare tire",
"spec": "full-size or compact, inflated to placard pressure",
"kind": "part"
},
{
"key": "car-jack",
"name": "Car jack",
"spec": "factory scissor jack or rated floor jack",
"kind": "tool"
},
{
"key": "lug-wrench",
"name": "Lug wrench",
"spec": "fits your lug size, often 17 to 21 mm",
"kind": "tool"
},
{
"key": "wheel-lock-key",
"name": "Wheel lock key",
"spec": "if equipped",
"kind": "tool"
},
{
"key": "wheel-chock",
"name": "Wheel chock",
"spec": "1 to 2",
"kind": "safety"
},
{
"key": "torque-wrench",
"name": "Torque wrench",
"spec": "1/2″ drive, typically 80 to 100 ft-lb per manual",
"kind": "measure"
},
{
"key": "socket-set",
"name": "Socket set",
"spec": "1/2″-drive deep socket matching lug nuts",
"kind": "tool"
},
{
"key": "tire-pressure-gauge",
"name": "Tire pressure gauge",
"spec": "",
"kind": "measure"
},
{
"key": "owners-manual",
"name": "Owner's manual",
"spec": "jack points, lug torque, spare limits",
"kind": "material"
},
{
"key": "flashlight",
"name": "Flashlight or headlamp",
"spec": "headlamp preferred",
"kind": "tool"
},
{
"key": "work-gloves",
"name": "Work gloves",
"spec": "",
"kind": "safety"
},
{
"key": "reflective-triangle",
"name": "Warning triangle",
"spec": "",
"kind": "safety"
},
{
"key": "reflective-vest",
"name": "Reflective vest",
"spec": "",
"kind": "safety"
},
{
"key": "kneeling-pad",
"name": "Kneeling pad",
"spec": "",
"kind": "safety"
},
{
"key": "small-container",
"name": "Small parts container",
"spec": "hubcap or cup for lug nuts",
"kind": "consumable"
}
],
"proTips": [
"Retorque the lug nuts to the manual's spec with a torque wrench as soon as you can, and recheck after 50 to 100 miles; lug nuts can settle and loosen after a wheel is refitted.",
"Check the spare's pressure before you need it; compact temporary spares often require about 60 psi and are limited to about 50 mph and short distances.",
"If a nut will not break loose, put the wrench arm horizontal and push down with your foot, using body weight rather than jumping on it."
],
"sources": [
"https://www.bfgoodrichtires.com/auto/learn/maintenance/how-to-change-a-tire",
"https://motorist.org/how-to-change-a-flat-tire-step-by-step-guide/",
"https://bridgestone-mea.com/en/discover/how-to-change-a-flat-tyre"
]
},
"check-oil": {
"items": [
{
"key": "motor-oil",
"name": "Motor oil",
"spec": "viscosity and spec per manual or oil cap (e.g. 0W-20), 1 qt",
"kind": "material"
},
{
"key": "engine-coolant",
"name": "Engine coolant (antifreeze)",
"spec": "type per manual, premixed 50/50, 1 gal",
"kind": "material"
},
{
"key": "washer-fluid",
"name": "Windshield washer fluid",
"spec": "1 gal, winter-rated in cold climates",
"kind": "material"
},
{
"key": "funnel",
"name": "Funnel",
"spec": "long-neck",
"kind": "tool"
},
{
"key": "shop-towels",
"name": "Shop towels",
"spec": "lint-free",
"kind": "consumable"
},
{
"key": "nitrile-gloves",
"name": "Nitrile gloves",
"spec": "",
"kind": "safety"
},
{
"key": "flashlight",
"name": "Flashlight or headlamp",
"spec": "",
"kind": "tool"
},
{
"key": "owners-manual",
"name": "Owner's manual",
"spec": "fluid types and capacities",
"kind": "material"
}
],
"proTips": [
"Check oil on level ground with the engine off a few minutes (or as the manual says) so oil drains back to the pan; checking on a slope gives a false reading.",
"The distance between MIN and MAX on most dipsticks is about 1 quart, so add a half quart at a time and recheck instead of guessing.",
"Never open a hot radiator or pressurized coolant cap; read the reservoir against its COLD marks with the engine cool, ideally after sitting a few hours."
],
"sources": [
"https://www.oreillyauto.com/how-to-hub/check-and-fill-fluids",
"https://www.mercuryinsurance.com/resources/basics-101/how-to-check-car-fluids.html",
"https://www.carsguide.com.au/car-advice/how-to-check-your-oil-coolant-and-windscreen-washer-levels-32454"
]
},
"wipers": {
"items": [
{
"key": "wiper-blade",
"name": "Wiper blade",
"spec": "driver and passenger lengths per fit guide, matching arm connector (J-hook, pin, etc.)",
"kind": "part"
},
{
"key": "towel",
"name": "Towel",
"spec": "folded thick",
"kind": "consumable"
},
{
"key": "tape-measure",
"name": "Tape measure",
"spec": "",
"kind": "measure"
},
{
"key": "glass-cleaner",
"name": "Glass cleaner",
"spec": "",
"kind": "consumable"
},
{
"key": "isopropyl-alcohol",
"name": "Isopropyl (rubbing) alcohol",
"spec": "to wipe new blade edge",
"kind": "consumable"
},
{
"key": "shop-towels",
"name": "Shop towels",
"spec": "",
"kind": "consumable"
},
{
"key": "washer-fluid",
"name": "Windshield washer fluid",
"spec": "for testing",
"kind": "material"
}
],
"proTips": [
"Some cars have a service position that parks wipers higher on the glass so the arms can be lifted; check the manual if the arms sit under the hood edge.",
"Clean the windshield thoroughly before fitting new blades; grit on the glass cuts a new rubber edge and causes streaks within days.",
"Many vehicles use different lengths and sometimes different connector types on each side, plus a rear blade; buy by the vehicle fit list, not by matching the old blades."
],
"sources": [
"https://www.rainx.com/instructions/fusion-blades/",
"https://www.autozone.com/diy/videos/how-to-remove-install-j-hook-wiper-blades-autozone-how-to-videos-177859530"
]
},
"bike-flat": {
"items": [
{
"key": "tire-levers",
"name": "Tire levers",
"spec": "2 to 3, plastic",
"kind": "tool"
},
{
"key": "inner-tube",
"name": "Inner tube",
"spec": "size from tire sidewall, matching valve type and length",
"kind": "part"
},
{
"key": "patch-kit",
"name": "Tube patch kit",
"spec": "glue or self-adhesive",
"kind": "material"
},
{
"key": "floor-pump",
"name": "Floor pump with gauge",
"spec": "head for Presta or Schrader",
"kind": "tool"
},
{
"key": "valve-adapter",
"name": "Presta-to-Schrader adapter",
"spec": "optional",
"kind": "tool"
},
{
"key": "tire-pressure-gauge",
"name": "Tire pressure gauge",
"spec": "if pump has none",
"kind": "measure"
},
{
"key": "hex-key-set",
"name": "Hex key set",
"spec": "for through-axle or bolt-on wheels",
"kind": "tool"
},
{
"key": "open-end-wrench",
"name": "Open-end wrench",
"spec": "15 mm, for axle nuts if no quick-release",
"kind": "tool"
},
{
"key": "rag",
"name": "Rag",
"spec": "",
"kind": "consumable"
},
{
"key": "chalk-or-marker",
"name": "Marker or chalk",
"spec": "",
"kind": "consumable"
},
{
"key": "bike-stand",
"name": "Bike repair stand",
"spec": "optional",
"kind": "tool"
},
{
"key": "nitrile-gloves",
"name": "Nitrile gloves",
"spec": "",
"kind": "safety"
}
],
"proTips": [
"Install the tire with its label lined up at the valve; when you find the tube hole, you can match it to the exact spot on the tire to find the culprit.",
"Before levering, push both beads into the deep center channel of the rim all the way around; this gives slack and often lets you finish installing by hand without pinching the tube.",
"Inflate to about 20 psi first and check that the bead line is even on both sides, then spin the wheel and look for wobbles before going to full pressure."
],
"sources": [
"https://www.parktool.com/en-us/blog/repair-help/tire-and-tube-removal-and-installation",
"https://www.parktool.com/en-us/blog/repair-help/inner-tube-repair"
]
},
"bike-brakes": {
"items": [
{
"key": "hex-key-set",
"name": "Hex key set",
"spec": "4 and 5 mm",
"kind": "tool"
},
{
"key": "open-end-wrench",
"name": "Open-end wrench",
"spec": "10 mm for pad and caliper nuts",
"kind": "tool"
},
{
"key": "torque-wrench",
"name": "Torque wrench",
"spec": "small Nm range, 6 to 8 Nm typical",
"kind": "measure"
},
{
"key": "brake-pads-rim",
"name": "Rim brake pads",
"spec": "matched to brake type and rim material",
"kind": "part"
},
{
"key": "isopropyl-alcohol",
"name": "Isopropyl (rubbing) alcohol",
"spec": "",
"kind": "consumable"
},
{
"key": "rag",
"name": "Rag",
"spec": "clean, lube-free",
"kind": "consumable"
},
{
"key": "sandpaper",
"name": "Fine sandpaper or emery cloth",
"spec": "fine, for glazed pads",
"kind": "consumable"
},
{
"key": "pick-tool",
"name": "Pick or awl",
"spec": "",
"kind": "tool"
},
{
"key": "bike-stand",
"name": "Bike repair stand",
"spec": "optional",
"kind": "tool"
},
{
"key": "nitrile-gloves",
"name": "Nitrile gloves",
"spec": "",
"kind": "safety"
}
],
"proTips": [
"Toe the pads in slightly so the front edge touches the rim first, leaving a small gap at the trailing edge; this reduces squeal.",
"Tighten caliper mounting nuts to the maker's spec, typically 6 to 7 Nm, while holding the caliper centered on the rim.",
"Pick out embedded glass and aluminum flecks from the pads; they cause grinding and score the rim."
],
"sources": [
"https://www.parktool.com/en-int/blog/repair-help/brake-pad-replacement-rim-brakes",
"https://www.parktool.com/en-us/blog/repair-help/dual-pivot-brake-service"
]
},
"bike-chain": {
"items": [
{
"key": "rag",
"name": "Rag",
"spec": "2 or more, lint-free",
"kind": "consumable"
},
{
"key": "degreaser",
"name": "Bike degreaser",
"spec": "bike-specific or citrus",
"kind": "material"
},
{
"key": "chain-lube",
"name": "Bike chain lubricant",
"spec": "wet or dry to suit conditions",
"kind": "material"
},
{
"key": "chain-scrubber",
"name": "Chain scrubber",
"spec": "optional",
"kind": "tool"
},
{
"key": "stiff-brush",
"name": "Stiff bristle brush",
"spec": "",
"kind": "tool"
},
{
"key": "bucket",
"name": "Bucket",
"spec": "water for rinsing",
"kind": "tool"
},
{
"key": "chain-checker",
"name": "Chain wear checker",
"spec": "",
"kind": "measure"
},
{
"key": "nitrile-gloves",
"name": "Nitrile gloves",
"spec": "",
"kind": "safety"
},
{
"key": "safety-glasses",
"name": "Safety glasses",
"spec": "when scrubbing",
"kind": "safety"
},
{
"key": "drop-cloth",
"name": "Drop cloth or cardboard",
"spec": "",
"kind": "consumable"
},
{
"key": "bike-stand",
"name": "Bike repair stand",
"spec": "optional",
"kind": "tool"
}
],
"proTips": [
"Check chain wear before cleaning; a chain past 0.5 percent (11 to 12 speed) or 0.75 percent stretch should be replaced, not cleaned, to save the cassette and chainrings.",
"Keep degreaser and lube off rims and disc rotors; cover brakes with a rag and wipe them with alcohol if any gets on.",
"Let the chain dry completely after rinsing before lubing; water or degreaser left inside the rollers dilutes the lube."
],
"sources": [
"https://www.parktool.com/en-us/blog/repair-help/chain-cleaning-with-a-park-tool-chain-scrubber",
"https://www.parktool.com/en-us/product/chain-and-drivetrain-cleaning-kit-cg-2-4"
]
}
};
