#!/usr/bin/env python3
"""Merge research output (research/out_*.json) into js/content/items.js.

Each input file: {"guides": {"<guideId>[@<variantId>]": {"items": [...], "proTips": [...], "sources": [...]}},
                  "items": {"<key>": {"name", "kind", "what", "uses", "tip"}}}
Usage: python3 scripts/build-items.py <research-dir>
"""
import glob, json, os, sys

src = sys.argv[1] if len(sys.argv) > 1 else 'research'
items, kits = {}, {}
for f in sorted(glob.glob(os.path.join(src, 'out_*.json'))):
    d = json.load(open(f))
    for k, v in d.get('items', {}).items():
        if k not in items or len(v.get('what', '')) > len(items[k].get('what', '')):
            items[k] = v
    kits.update(d.get('guides', {}))
missing = sorted({it['key'] for g in kits.values() for it in g['items'] if it['key'] not in items})
for k in missing:  # fall back to a stub so the UI never breaks
    items[k] = {'name': k.replace('-', ' ').capitalize(), 'kind': 'material', 'what': '', 'uses': [], 'tip': ''}
out = os.path.join(os.path.dirname(__file__), '..', 'js', 'content', 'items.js')
with open(out, 'w') as fh:
    fh.write('/* Generated by scripts/build-items.py from web research: complete kit lists per guide (TB.KITS)\n   and the item dictionary (TB.ITEMS). Do not edit by hand. */\nwindow.TB = window.TB || {};\n')
    fh.write('TB.ITEMS = ' + json.dumps(dict(sorted(items.items())), ensure_ascii=False, indent=0) + ';\n')
    fh.write('TB.KITS = ' + json.dumps(kits, ensure_ascii=False, indent=0) + ';\n')
print(f'{len(kits)} kits, {len(items)} items, {len(missing)} stubbed: {missing[:10]}')
